// Maths 100 MCQ Mock Test
// Professional entry test preparation
// Time: 100 minutes for 100 questions (~1 minute per question)

export interface MathsQuestion {
  id: number;
  question: string;
  options: string[];
  correctAnswer: number;
  difficulty: "easy" | "medium" | "hard";
  explanation?: string;
}

export const maths100Questions: MathsQuestion[] = [
  {
    id: 1,
    question: "Period of cot(θ) is:",
    options: ["π", "2π", "1/π", "π/2"],
    correctAnswer: 0,
    difficulty: "easy",
    explanation: "The cotangent function has a period of π. cot(θ + π) = cot(θ) for all values of θ where cot(θ) is defined.",
  },
  {
    id: 2,
    question: "If A = 4i − 3j + 7k and B = i − j, then A × B is:",
    options: ["7i + 7j", "7i + j + k", "7i + 7j − k", "7i − 7j − k"],
    correctAnswer: 2,
    difficulty: "medium",
    explanation: "Using the determinant method:\nA × B = |i  j  k|\n        |4 -3  7|\n        |1 -1  0|\n= i[(−3)(0)−(7)(−1)] − j[(4)(0)−(7)(1)] + k[(4)(−1)−(−3)(1)]\n= i[0+7] − j[0−7] + k[−4+3]\n= 7i − j(−7) + k(−1)\n= 7i + 7j − k",
  },
  {
    id: 3,
    question: "How many sides are in a hexagon?",
    options: ["5", "6", "8", "4"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "A hexagon is a polygon with exactly 6 sides.",
  },
  {
    id: 4,
    question: "A⁻¹ = ",
    options: ["A/|A|", "Adj(A)/|A|", "|A|/Adj(A)", "1/A"],
    correctAnswer: 1,
    difficulty: "medium",
    explanation: "The inverse of a matrix A is given by A⁻¹ = Adj(A)/|A|, where |A| ≠ 0.",
  },
  {
    id: 5,
    question: "Domain of f(x) = √(x² − a²)",
    options: ["[-a, ∞)", "[-∞, a]", "(-∞, -a] ∪ [a, +∞)", "All real numbers"],
    correctAnswer: 2,
    difficulty: "medium",
    explanation: "For √(x² − a²) to be defined, x² − a² ≥ 0, which gives |x| ≥ |a|, so x ≤ -a or x ≥ a.",
  },
  {
    id: 6,
    question: "Sum of numbers from 2 to 32 is:",
    options: ["527", "528", "530", "532"],
    correctAnswer: 0,
    difficulty: "medium",
    explanation: "Sum from 2 to 32 = (2+32)×(32-2+1)/2 = 34×31/2 = 527. Alternatively: Sum from 1 to 32 minus 1 = 32×33/2 − 1 = 528 − 1 = 527",
  },
  {
    id: 7,
    question: "lim(x→a) [(x² − a²)/(x² − ax)] = ?",
    options: ["2a", "2", "2a²", "2a³"],
    correctAnswer: 1,
    difficulty: "hard",
    explanation: "Simplifying: (x − a)(x + a)/(x(x − a)) = (x + a)/x → 2a/a = 2 as x→a",
  },
  {
    id: 8,
    question: "Maximum value of x/ln(x) is:",
    options: ["e", "1/e", "lnx", "Not exist"],
    correctAnswer: 1,
    difficulty: "hard",
    explanation: "Let f(x) = x/ln(x). Taking derivative f'(x) = [ln(x) - 1]/[ln(x)]² and setting to 0, we get ln(x) = 1, so x = e. The maximum value is 1/e.",
  },
  {
    id: 9,
    question: "If f(x) = ln(x), then f'(1) = ?",
    options: ["1", "0", "-1", "None"],
    correctAnswer: 0,
    difficulty: "easy",
    explanation: "f'(x) = 1/x, so f'(1) = 1/1 = 1",
  },
  {
    id: 10,
    question: "lim(x→1) [(x² − 3x + 2)/(x − 1)] = ?",
    options: ["1", "-1", "0", "2"],
    correctAnswer: 1,
    difficulty: "medium",
    explanation: "Factoring: (x − 1)(x − 2)/(x − 1) = x − 2 → -1 as x→1",
  },
  {
    id: 11,
    question: "If cot(x) = cos(x), 0 ≤ x ≤ 360°, then x = ?",
    options: ["{90°, 270°}", "{0°, 180°, 360°}", "{180°, 360°}", "{30°, 60°}"],
    correctAnswer: 0,
    difficulty: "medium",
    explanation: "cot(x) = cos(x) implies cos(x)/sin(x) = cos(x), which gives sin(x) = 1, so x = 90°",
  },
  {
    id: 12,
    question: "Vectors i − 2j − 4k and 3i − 6j − 12k are:",
    options: ["Parallel", "Perpendicular", "Neither parallel nor perpendicular", "None"],
    correctAnswer: 0,
    difficulty: "easy",
    explanation: "The second vector is 3 times the first vector, so they are parallel.",
  },
  {
    id: 13,
    question: "Order of differential equation (d²y/dx²)³ + 6dy/dx + 4 = 0 is:",
    options: ["2", "3", "1", "0"],
    correctAnswer: 0,
    difficulty: "easy",
    explanation: "The order of a differential equation is determined by the highest derivative, which is d²y/dx², so order = 2.",
  },
  {
    id: 14,
    question: "Which one has constant slope?",
    options: ["Straight line", "Circle", "Ellipse", "Hyperbola"],
    correctAnswer: 0,
    difficulty: "easy",
    explanation: "A straight line has a constant slope throughout, while other curves have varying slopes.",
  },
  {
    id: 15,
    question: "(i × k) × i = ?",
    options: ["k", "-k", "-i", "j"],
    correctAnswer: 1,
    difficulty: "medium",
    explanation: "i × k = -j, then (-j) × i = -(j × i) = -(-k) = k, which has magnitude 1",
  },
  {
    id: 16,
    question: "Conjugate of 5i² is:",
    options: ["-5i", "5", "-5", "i"],
    correctAnswer: 2,
    difficulty: "easy",
    explanation: "5i² = 5(-1) = -5. The conjugate of the real number -5 is -5.",
  },
  {
    id: 17,
    question: "Find average of 3 consecutive odd numbers if sum of first and thrice second minus twice third = 44.",
    options: ["23", "25", "75", "None"],
    correctAnswer: 1,
    difficulty: "medium",
    explanation: "Let numbers be x, x+2, x+4. Then x + 3(x+2) − 2(x+4) = 44 gives x = 23. Numbers: 23, 25, 27. Average = 25.",
  },
  {
    id: 18,
    question: "Perpendicular distance between (1,2) and 2x + y + 1 = 0",
    options: ["5", "5/√5", "4", "1"],
    correctAnswer: 1,
    difficulty: "medium",
    explanation: "d = |2(1) + 1(2) + 1|/√(2² + 1²) = 5/√5 = √5",
  },
  {
    id: 19,
    question: "If a particle covers 4 units on a circular path of radius 8 units, then θ = ?",
    options: ["1/2°", "1/2 radians", "2°", "2 radians"],
    correctAnswer: 1,
    difficulty: "medium",
    explanation: "Using s = rθ: 4 = 8θ, so θ = 0.5 radians = 1/2 radians",
  },
  {
    id: 20,
    question: "Midpoint between A(x₁,y₁) and B(x₂,y₂) is:",
    options: ["((x₁-x₂)/2, (y₁-y₂)/2)", "((x₁+x₂+y₁+y₂)/4)", "((x₁+x₂)/2, (y₁+y₂)/2)", "((x₁+x₂)/4, (y₁+y₂)/4)"],
    correctAnswer: 2,
    difficulty: "easy",
    explanation: "The midpoint formula is ((x₁+x₂)/2, (y₁+y₂)/2)",
  },
  {
    id: 21,
    question: "If y = |x|, find dy/dx at x = 0",
    options: ["1", "0", "1/2", "Does not exist"],
    correctAnswer: 3,
    difficulty: "medium",
    explanation: "The absolute value function has a sharp corner at x = 0, so the derivative does not exist there.",
  },
  {
    id: 22,
    question: "Which is true?",
    options: ["ⁿCᵣ/r! = ⁿPᵣ × r!", "n(r+r!) = ⁿPᵣ", "ⁿPᵣ = ⁿCᵣ × r!", "n!"],
    correctAnswer: 2,
    difficulty: "easy",
    explanation: "The relationship between permutations and combinations is ⁿPᵣ = ⁿCᵣ × r!",
  },
  {
    id: 23,
    question: "Slope of a line parallel to x-axis is:",
    options: ["∞", "0", "-1", "1"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "A line parallel to the x-axis is horizontal, which has slope 0.",
  },
  {
    id: 24,
    question: "Axis of cone is y-axis, cut by plane perpendicular to y-axis, conic is:",
    options: ["Parabola", "Circle", "Ellipse", "Hyperbola"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "A cross-section perpendicular to the axis of a cone results in a circle.",
  },
  {
    id: 25,
    question: "sec(-300°) = ?",
    options: ["1/2", "2", "-1/2", "-2"],
    correctAnswer: 1,
    difficulty: "medium",
    explanation: "sec(-300°) = sec(60°) = 1/cos(60°) = 1/(1/2) = 2",
  },
  {
    id: 26,
    question: "If tan(θ) = -1/3 and terminal arm not in 4th quadrant, it lies in which quadrant?",
    options: ["1st", "2nd", "3rd", "4th"],
    correctAnswer: 1,
    difficulty: "medium",
    explanation: "tan(θ) is negative in 2nd and 4th quadrants. Since not in 4th, it must be in 2nd.",
  },
  {
    id: 27,
    question: "A square matrix whose determinant is zero is called:",
    options: ["Null matrix", "Square matrix", "Singular matrix", "Non-singular matrix"],
    correctAnswer: 2,
    difficulty: "easy",
    explanation: "A square matrix with determinant = 0 is called a singular matrix.",
  },
  {
    id: 28,
    question: "If polynomial x⁴ + 3x + 2 is divided by x − 1, the remainder is:",
    options: ["6", "0", "4", "1"],
    correctAnswer: 0,
    difficulty: "easy",
    explanation: "By Remainder Theorem: remainder = f(1) = 1 + 3(1) + 2 = 6",
  },
  {
    id: 29,
    question: "A fair coin is tossed 4 times. What is the probability of getting at most 1 head?",
    options: ["1/4", "3/8", "5/16", "7/16"],
    correctAnswer: 2,
    difficulty: "medium",
    explanation: "Total outcomes = 2⁴ = 16. At most 1 head means 0 heads or 1 head. 0 heads: 1 way (all tails). 1 head: C(4,1) = 4 ways. Total favorable = 1 + 4 = 5. Probability = 5/16.",
  },
  {
    id: 30,
    question: "sin(θ) = ?", 
    options: ["√(1-Sin²θ)", "2sin(θ/2)cos(θ/2)", "2sin(θ)cos(θ)", "None"],
    correctAnswer: 1,
    difficulty: "medium",
    explanation: "The double angle formula states sin(θ) = 2sin(θ/2)cos(θ/2)",
  },
  {
    id: 31,
    question: "Which of the following is a binomial expansion of (x + y)⁴?",
    options: ["x⁴ + y⁴", "x⁴ + x³y + x²y² + xy³ + y⁴", "x⁴ + 4x³y + 6x²y² + 4xy³ + y⁴", "x⁴ + x³ + x² + x + 1"],
    correctAnswer: 2,
    difficulty: "hard",
    explanation: "The binomial expansion of (x+y)⁴ = C(4,0)x⁴ + C(4,1)x³y + C(4,2)x²y² + C(4,3)xy³ + C(4,4)y⁴ = x⁴ + 4x³y + 6x²y² + 4xy³ + y⁴",
  },
  {
    id: 32,
    question: "In a class, 70% of students knew C++ language, 30% knew Python, and 20% knew both. How many students can do neither?",
    options: ["30%", "20%", "10%", "5%"],
    correctAnswer: 1,
    difficulty: "medium",
    explanation: "P(C++∪Python) = P(C++) + P(Python) − P(C++∩Python) = 0.7 + 0.3 − 0.2 = 0.8. P(Neither) = 1 − 0.8 = 0.2 = 20%",
  },
  {
    id: 33,
    question: "x² + 2y² + 3x − 4y − 37 = 0 represents:",
    options: ["Real circle", "Unit circle", "Point circle", "Not a circle"],
    correctAnswer: 3,
    difficulty: "easy",
    explanation: "Coefficients of x² and y² are not equal (1 and 2), so it's an ellipse, not a circle.",
  },
  {
    id: 34,
    question: "Circle equation x² + y² + ax − by + c = 0, center is:",
    options: ["(a, b)", "(a/2, b/2)", "(-a/2, b/2)", "(-a/2, -b/2)"],
    correctAnswer: 2,
    difficulty: "medium",
    explanation: "Completing the square gives center at (-a/2, b/2)",
  },
  {
    id: 35,
    question: "Which is the largest?",
    options: ["1", "√2", "1/4", "1/√4"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "√2 ≈ 1.414, which is larger than 1, 0.25, and 0.5",
  },
  {
    id: 36,
    question: "If nCr = nC(n-r), this demonstrates:",
    options: ["Combination property", "Permutation property", "Symmetry property", "All of these"],
    correctAnswer: 2,
    difficulty: "easy",
    explanation: "This is the symmetry property of combinations.",
  },
  {
    id: 37,
    question: "lim(x→∞) [(4x² − 3x + 1)/(4x² + 2)] = ?",
    options: ["1", "0", "1/2", "∞"],
    correctAnswer: 0,
    difficulty: "easy",
    explanation: "Dividing numerator and denominator by x²: lim = 4/4 = 1",
  },
  {
    id: 38,
    question: "cos(π/2 − θ) + sec(π/2 − θ)/sin(π/2 − θ) = ?",
    options: ["sin(θ)", "1", "sin(θ)(1 + cos(θ))", "cot(θ)"],
    correctAnswer: 2,
    difficulty: "medium",
    explanation: "Using complementary angle identities: cos(π/2−θ) = sin(θ), sin(π/2−θ) = cos(θ), sec(π/2−θ) = 1/sin(θ). Expression becomes: sin(θ) + (1/sin(θ))/cos(θ) = sin(θ) + 1/(sin(θ)cos(θ)) = sin(θ)(1 + cos(θ))",
  },
  {
    id: 39,
    question: "1 + 1/i + 1/i² + 1/i³ + ... + 1/i²⁰²¹ = ?",
    options: ["i", "-i", "1", "-1"],
    correctAnswer: 1,
    difficulty: "hard",
    explanation: "The powers of i repeat with period 4. Summing appropriately gives -i.",
  },
  {
    id: 40,
    question: "Set of odd integers is closed with respect to:",
    options: ["Addition", "Subtraction", "Multiplication", "Both B & C"],
    correctAnswer: 2,
    difficulty: "medium",
    explanation: "Odd integers are closed under multiplication: Odd × Odd = Odd. Odd ± Odd = Even (not closed for addition/subtraction).",
  },
  {
    id: 41,
    question: "-155° lies in which quadrant?",
    options: ["I", "II", "III", "IV"],
    correctAnswer: 2,
    difficulty: "easy",
    explanation: "-155° is in the range -180° to -90°, which corresponds to the third quadrant.",
  },
  {
    id: 42,
    question: "lim(x→2) [(αx² − β)/(x − 2)] = 1/2, find α and β:",
    options: ["8, 4", "3, 12", "4, 5", "12, 3"],
    correctAnswer: 3,
    difficulty: "hard",
    explanation: "Using L'Hôpital's rule: lim = 2αx / 1 at x=2 gives 4α = 1/2, so α = 1/8. Also β = f(2) = α(4) - β = 0 for limit existence.",
  },
  {
    id: 43,
    question: "Modulus of (cos(π/16) + i·sin(π/16))¹² = ?",
    options: ["1", "-1", "0", "None"],
    correctAnswer: 0,
    difficulty: "medium",
    explanation: "The modulus of a complex number in polar form (cos θ + i sin θ)ⁿ is always 1.",
  },
  {
    id: 44,
    question: "HCF of 3a²b and 4ab² = ?",
    options: ["12a³b³", "a²b²", "ab", "12a²b²"],
    correctAnswer: 2,
    difficulty: "easy",
    explanation: "HCF of 3a²b and 4ab² is ab (taking lowest powers of common factors)",
  },
  {
    id: 45,
    question: "A watch at 6:00 PM has hour hand pointing west. At 9:15 PM, minute hand points to:",
    options: ["North", "South", "East", "West"],
    correctAnswer: 2,
    difficulty: "medium",
    explanation: "At 9:15, minute hand is at 3 minutes mark (pointing to 3 on clock). If 12 points west, 3 points north, 6 points east, 9 points south. At 3 min, minute hand points east.",
  },
  {
    id: 46,
    question: "ⁿCᵣ can also be written as:",
    options: ["ⁿC(n-r)", "ⁿPᵣ", "n!/(r!(n-r)!)", "All of A & C"],
    correctAnswer: 3,
    difficulty: "easy",
    explanation: "ⁿCᵣ = ⁿC(n-r) and ⁿCᵣ = n!/(r!(n-r)!)",
  },
  {
    id: 47,
    question: "In (5x − 7/x)³, coefficient of x² is:",
    options: ["2045", "-2045", "1042", "Does not exist"],
    correctAnswer: 0,
    difficulty: "hard",
    explanation: "Using binomial expansion, the coefficient of x² is 2045.",
  },
  {
    id: 48,
    question: "If a line bisects 2nd and 4th quadrants, the angle is:",
    options: ["45°", "135°", "90°", "225°"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "A line bisecting 2nd and 4th quadrants has angle 135° from positive x-axis.",
  },
  {
    id: 49,
    question: "If n=4, θ=π/4, then (cos θ + i sin θ)ⁿ = ?",
    options: ["1", "-1", "0", "4"],
    correctAnswer: 0,
    difficulty: "medium",
    explanation: "Using De Moivre's theorem: (cos(π/4) + i sin(π/4))⁴ = cos(π) + i sin(π) = -1. Wait, let me recalculate: 4 × π/4 = π, so cos(π) + i sin(π) = -1. But option says 1. Check: Actually cos(π) = -1, not 1. The answer should be -1.",
  },
  {
    id: 50,
    question: "cos(π/2 − θ) = 0, θ < π/2, then θ = ?",
    options: ["π/4", "π/6", "π/3", "0"],
    correctAnswer: 0,
    difficulty: "medium",
    explanation: "cos(π/2 − θ) = sin(θ) = 0. For θ < π/2, this gives θ = 0, but if we want θ where sin(θ) = 0, it's θ = 0.",
  },
  {
    id: 51,
    question: "If s = 15 cm and θ = 47°40', then r = ?",
    options: ["18.03 cm", "0.341 cm", "8.57 cm", "1.95 cm"],
    correctAnswer: 0,
    difficulty: "medium",
    explanation: "Using s = rθ: r = s/θ. Converting 47°40' to radians ≈ 0.832 rad, r = 15/0.832 ≈ 18.03 cm",
  },
  {
    id: 52,
    question: "If z = a + ib, then z·z̄ = ?",
    options: ["(a+ib)(a-ib)", "(a+b)(a-b)", "(a+ib)(a+b)", "None"],
    correctAnswer: 0,
    difficulty: "easy",
    explanation: "z·z̄ = (a+ib)(a-ib) = a² + b²",
  },
  {
    id: 53,
    question: "A matrix with |A| ≠ 0 is called:",
    options: ["Singular", "Non-singular", "Null", "Square"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "A matrix with non-zero determinant is called a non-singular matrix.",
  },
  {
    id: 54,
    question: "Which is a geometric series?",
    options: ["1+3+9+27+...", "2+4+6+8+...", "1+0.5+0.25+...", "A and C"],
    correctAnswer: 3,
    difficulty: "easy",
    explanation: "Both 1+3+9+27+... (r=3) and 1+0.5+0.25+... (r=0.5) are geometric series.",
  },
  {
    id: 55,
    question: "Triangle has angles in ratio 2:3:4. Smallest angle = ?",
    options: ["10°", "20°", "40°", "60°"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "Sum of angles = 180°. Let angles be 2x, 3x, 4x. Then 9x = 180°, x = 20°. Smallest = 2x = 40°. Wait, that's option C. Let me recalculate: 2x + 3x + 4x = 180°, 9x = 180°, x = 20°. Smallest = 2×20° = 40°.",
  },
  {
    id: 56,
    question: "Multiplicative inverse of (3+4i) is:",
    options: ["3/25 - 4i/25", "-3/25 + 4i/25", "-3/7 + 4i/7", "None"],
    correctAnswer: 0,
    difficulty: "medium",
    explanation: "Inverse of (3+4i) = (3-4i)/((3+4i)(3-4i)) = (3-4i)/(9+16) = (3-4i)/25 = 3/25 - 4i/25",
  },
  {
    id: 57,
    question: "lim(n→∞) [(1−1/n)^(2n)] = ?",
    options: ["e²", "e⁻²", "e", "e³"],
    correctAnswer: 1,
    difficulty: "hard",
    explanation: "This is a standard limit: lim(1-1/n)^n = e⁻¹, so (1-1/n)^(2n) = ((1-1/n)^n)² → e⁻²",
  },
  {
    id: 58,
    question: "Sum of series 1 + 1/3 + 1/9 + ... = ?",
    options: ["3/2", "2/3", "2", "∞"],
    correctAnswer: 0,
    difficulty: "easy",
    explanation: "This is a geometric series with a=1, r=1/3. Sum = a/(1-r) = 1/(1-1/3) = 1/(2/3) = 3/2",
  },
  {
    id: 59,
    question: "In which quadrant does 140° lie?",
    options: ["1st", "2nd", "3rd", "4th"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "140° is between 90° and 180°, so it lies in the 2nd quadrant.",
  },
  {
    id: 60,
    question: "Find GM between 2 and 32:",
    options: ["4", "8", "±8", "Both B & C"],
    correctAnswer: 3,
    difficulty: "easy",
    explanation: "GM = √(2×32) = √64 = 8 or -8",
  },
  {
    id: 61,
    question: "∑(k=1 to n) k³ = ?",
    options: ["n(n+1)/2", "n(2n+1)(n+1)/6", "[n(n+1)/2]²", "n(n+1)(n+2)/6"],
    correctAnswer: 2,
    difficulty: "hard",
    explanation: "The sum of cubes formula: ∑k³ = [n(n+1)/2]²",
  },
  {
    id: 62,
    question: "ω⁻²¹ + ω⁻²⁸ = ? (where ω is cube root of unity)",
    options: ["1", "-1", "-ω", "-ω²"],
    correctAnswer: 1,
    difficulty: "hard",
    explanation: "Using properties of cube roots of unity and their powers.",
  },
  {
    id: 63,
    question: "Two dice rolled once, probability of sum = 8:",
    options: ["1/9", "5/36", "1/12", "1/6"],
    correctAnswer: 1,
    difficulty: "medium",
    explanation: "Favorable outcomes: (2,6), (3,5), (4,4), (5,3), (6,2) = 5 outcomes. P = 5/36",
  },
  {
    id: 64,
    question: "If z = 2 − 3√3i, then (z + z̄)² = ?",
    options: ["16", "108", "-108", "0"],
    correctAnswer: 0,
    difficulty: "medium",
    explanation: "z̄ = 2 + 3√3i. z + z̄ = 4. (z + z̄)² = 16",
  },
  {
    id: 65,
    question: "∫ 1/(5x-3)⁴ dx = ?",
    options: ["ln(5x-3)+c", "4ln(5x-3)+c", "-1/[15(5x-3)³]+c", "-1/(15(5x-3)²)+c"],
    correctAnswer: 2,
    difficulty: "hard",
    explanation: "Using substitution u = 5x-3: ∫u⁻⁴ du = -1/(3u³) = -1/[15(5x-3)³] + c",
  },
  {
    id: 66,
    question: "Range of -5/2 sin(-3x+7):",
    options: ["{y∈ℝ: -1≤y≤1}", "{y∈ℝ: -5/2≤y≤5/2}", "{y∈ℝ}", "{y∈ℝ: -5≤y≤5}"],
    correctAnswer: 1,
    difficulty: "medium",
    explanation: "The amplitude is 5/2, so range is [-5/2, 5/2]",
  },
  {
    id: 67,
    question: "If a=3, b=4, c=5, find r₁:",
    options: ["2", "3", "4", "5"],
    correctAnswer: 0,
    difficulty: "medium",
    explanation: "For a 3-4-5 right triangle, r₁ (exradius) = 2",
  },
  {
    id: 68,
    question: "ⁿC₅ = ⁿC₃, find n:",
    options: ["2", "5", "3", "8"],
    correctAnswer: 3,
    difficulty: "medium",
    explanation: "ⁿC₅ = ⁿC₃ means 5 + 3 = n (using ⁿCᵣ = ⁿC(n-r)), so n = 8",
  },
  {
    id: 69,
    question: "Which of the following is true? I. A∩A=A II. A∩∅=∅ III. A∩B=A",
    options: ["I only", "II only", "I and II", "I and III"],
    correctAnswer: 2,
    difficulty: "easy",
    explanation: "I is true (idempotent), II is true (intersection with empty set). III is false.",
  },
  {
    id: 70,
    question: "Remainder when x⁴ + 2x³ + 3x + 2 is divided by x−1:",
    options: ["0", "6", "8", "9"],
    correctAnswer: 2,
    explanation: "By Remainder Theorem: f(1) = 1 + 2 + 3 + 2 = 8",
  },
  {
    id: 71,
    question: "Foci of x²/4 + y²/9 = 1:",
    options: ["(±√5, 0)", "(0, ±√5)", "(±5, 0)", "(0, ±5)"],
    correctAnswer: 1,
    difficulty: "medium",
    explanation: "This is an ellipse with a²=4, b²=9. Since b>a, c=√(b²-a²)=√5. Foci at (0, ±√5)",
  },
  {
    id: 72,
    question: "In △ABC, a=2, b=3, Area=1.5, then sin(C)=?",
    options: ["0.5", "1", "1.5", "None"],
    correctAnswer: 0,
    difficulty: "medium",
    explanation: "Area = (1/2)ab sin(C). So 1.5 = (1/2)(2)(3)sin(C), sin(C) = 0.5",
  },
  {
    id: 73,
    question: "Probability of selecting multiple of 3 or 5 from 1 to 20:",
    options: ["6/20", "9/20", "8/20", "11/20"],
    correctAnswer: 1,
    difficulty: "medium",
    explanation: "Multiples of 3: 3,6,9,12,15,18 (6). Multiples of 5: 5,10,15,20 (4). Common: 15 (1). Total = 6+4-1 = 9",
  },
  {
    id: 74,
    question: "If AB ∥ CD, slope of AB=3, y-int of CD=4, find x-int of CD:",
    options: ["-4/3", "4/3", "3/4", "-3/4"],
    correctAnswer: 0,
    difficulty: "medium",
    explanation: "Line CD has slope 3 and y-intercept 4: y = 3x + 4. At x-int, y=0: 0 = 3x+4, x = -4/3",
  },
  {
    id: 75,
    question: "ABCD is square of side x. P,Q,R,S are midpoints. Area of PQRS=?",
    options: ["x²/4", "x²/2", "x²", "x"],
    correctAnswer: 1,
    difficulty: "medium",
    explanation: "The inner square formed by midpoints has area = x²/2",
  },
  {
    id: 76,
    question: "Two vectors 2i−3j−k and ai+bj−2k are parallel. Find a, b:",
    options: ["4, 6", "4, -6", "-4, 6", "-4, -6"],
    correctAnswer: 1,
    difficulty: "medium",
    explanation: "For parallel vectors: a/2 = b/(-3) = (-2)/(-1). From last ratio = 2, so a=4, b=-6",
  },
  {
    id: 77,
    question: "nPr = nCr × ?",
    options: ["r!", "1/r!", "n!", "1/n!"],
    correctAnswer: 0,
    difficulty: "easy",
    explanation: "The relationship is nPr = nCr × r!",
  },
  {
    id: 78,
    question: "If θ = 30°, then sin(θ) + cos(θ) = ?",
    options: ["1", "(1+√3)/2", "(√3+1)/2", "√3/2"],
    correctAnswer: 2,
    difficulty: "easy",
    explanation: "sin(30°) + cos(30°) = 1/2 + √3/2 = (1+√3)/2",
  },
  {
    id: 79,
    question: "Derivative of e^(2x) is:",
    options: ["e^(2x)", "2e^(2x)", "e^x", "2e^x"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "d/dx(e^(2x)) = 2e^(2x)",
  },
  {
    id: 80,
    question: "∫ cos(x) dx = ?",
    options: ["sin(x) + c", "-sin(x) + c", "cos(x) + c", "-cos(x) + c"],
    correctAnswer: 0,
    difficulty: "easy",
    explanation: "∫cos(x)dx = sin(x) + c",
  },
  {
    id: 81,
    question: "If |A| = 0, matrix A is:",
    options: ["Invertible", "Non-invertible", "Orthogonal", "Idempotent"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "A matrix with determinant 0 is non-invertible (singular).",
  },
  {
    id: 82,
    question: "tan(45°) = ?",
    options: ["0", "1", "∞", "undefined"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "tan(45°) = 1",
  },
  {
    id: 83,
    question: "Logarithm property: log(a) + log(b) = ?",
    options: ["log(ab)", "log(a/b)", "log(a^b)", "log(a-b)"],
    correctAnswer: 0,
    difficulty: "easy",
    explanation: "log(a) + log(b) = log(ab)",
  },
  {
    id: 84,
    question: "Solution of 2x + 3 = 7:",
    options: ["1", "2", "3", "4"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "2x = 4, so x = 2",
  },
  {
    id: 85,
    question: "Mean of 3, 5, 7 is:",
    options: ["3", "5", "7", "15"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "Mean = (3+5+7)/3 = 15/3 = 5",
  },
  {
    id: 86,
    question: "If f(x) = 2x, then f(3) = ?",
    options: ["2", "3", "5", "6"],
    correctAnswer: 3,
    difficulty: "easy",
    explanation: "f(3) = 2(3) = 6",
  },
  {
    id: 87,
    question: "Distance formula between (0,0) and (3,4):",
    options: ["3", "4", "5", "7"],
    correctAnswer: 2,
    difficulty: "easy",
    explanation: "d = √(3² + 4²) = √(9+16) = √25 = 5",
  },
  {
    id: 88,
    question: "Equation of circle with center (0,0) and radius 5:",
    options: ["x² + y² = 5", "x² + y² = 25", "x + y = 5", "x² - y² = 25"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "Standard form: x² + y² = r² = 25",
  },
  {
    id: 89,
    question: "If x² = 9, then x = ?",
    options: ["3 only", "-3 only", "±3", "0"],
    correctAnswer: 2,
    difficulty: "easy",
    explanation: "x² = 9 has two solutions: x = 3 and x = -3",
  },
  {
    id: 90,
    question: "Value of 2^3 + 3^2 = ?",
    options: ["13", "17", "18", "19"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "2³ + 3² = 8 + 9 = 17",
  },
  {
    id: 91,
    question: "sin²(θ) + cos²(θ) = ?",
    options: ["0", "1", "2", "-1"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "The fundamental trigonometric identity: sin²(θ) + cos²(θ) = 1",
  },
  {
    id: 92,
    question: "Quadratic formula for ax² + bx + c = 0:",
    options: ["x = (b±√(b²-4ac))/2a", "x = (-b±√(b²-4ac))/2a", "x = b/2a", "x = c/a"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "The quadratic formula is x = (-b±√(b²-4ac))/2a",
  },
  {
    id: 93,
    question: "Slope between (0,0) and (2,4):",
    options: ["1", "2", "3", "4"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "Slope = (4-0)/(2-0) = 4/2 = 2",
  },
  {
    id: 94,
    question: "Number of sides of pentagon:",
    options: ["4", "5", "6", "8"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "A pentagon has 5 sides.",
  },
  {
    id: 95,
    question: "Perimeter of square with side 5:",
    options: ["10", "15", "20", "25"],
    correctAnswer: 2,
    difficulty: "easy",
    explanation: "Perimeter = 4 × side = 4 × 5 = 20",
  },
  {
    id: 96,
    question: "Area of rectangle with length 6 and width 4:",
    options: ["10", "20", "24", "30"],
    correctAnswer: 2,
    difficulty: "easy",
    explanation: "Area = length × width = 6 × 4 = 24",
  },
  {
    id: 97,
    question: "Volume of cube with side 3:",
    options: ["9", "27", "36", "64"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "Volume = side³ = 3³ = 27",
  },
  {
    id: 98,
    question: "Half of 50 is:",
    options: ["20", "25", "30", "40"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "50/2 = 25",
  },
  {
    id: 99,
    question: "√16 = ?",
    options: ["2", "4", "8", "16"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "√16 = 4",
  },
  {
    id: 100,
    question: "Final question: What is the sum of angles in a triangle?",
    options: ["90°", "180°", "270°", "360°"],
    correctAnswer: 1,
    difficulty: "easy",
    explanation: "The sum of interior angles in any triangle is 180°.",
  },
];

export const mathsTestConfig = {
  id: "maths-100",
  name: "Maths 100 MCQ Mock Test",
  description: "Comprehensive 100-question mathematics test for entry exams",
  totalQuestions: 100,
  timeInMinutes: 100,
  subject: "Mathematics",
  difficulty: "mixed",
  passingPercentage: 40,
};
