export interface Question {
  id: number;
  question: string;
  options: string[];
  correctAnswer: number;
  subject: string;
  difficulty: "easy" | "medium" | "hard";
}

export interface TestCategory {
  id: string;
  name: string;
  description: string;
  subjects: string[];
  totalQuestions: number;
  timeInMinutes: number;
  difficulty: string;
  color: string;
}

export const testCategories: TestCategory[] = [
  {
    id: "engineering",
    name: "Engineering Entry Test",
    description: "Engineering",
    subjects: ["Physics", "Chemistry", "Mathematics"],
    totalQuestions: 200,
    timeInMinutes: 180,
    difficulty: "mixed",
    color: "bg-blue-500",
  },
  {
    id: "applied-sciences",
    name: "Applied Sciences",
    description: "Applied Sciences",
    subjects: ["Biology", "Chemistry", "Physics"],
    totalQuestions: 200,
    timeInMinutes: 180,
    difficulty: "mixed",
    color: "bg-green-500",
  },
  {
    id: "architecture",
    name: "Architecture",
    description: "Architecture",
    subjects: ["Advanced Maths", "Design Aptitude"],
    totalQuestions: 200,
    timeInMinutes: 180,
    difficulty: "mixed",
    color: "bg-orange-500",
  },
  {
    id: "business",
    name: "Business",
    description: "Business",
    subjects: ["Basic Maths", "English"],
    totalQuestions: 200,
    timeInMinutes: 180,
    difficulty: "mixed",
    color: "bg-purple-500",
  },
];

// 180 MCQ Questions - Replace or modify these as needed
export const allQuestions: Question[] = [
  // ========== PHYSICS (30 Questions) ==========
  {
    id: 1,
    question: "What is the SI unit of force?",
    options: ["Joule", "Newton", "Watt", "Pascal"],
    correctAnswer: 1,
    subject: "Physics",
    difficulty: "easy",
  },
  {
    id: 2,
    question: "The speed of light in vacuum is approximately:",
    options: ["3 × 10⁶ m/s", "3 × 10⁷ m/s", "3 × 10⁸ m/s", "3 × 10⁹ m/s"],
    correctAnswer: 2,
    subject: "Physics",
    difficulty: "easy",
  },
  {
    id: 3,
    question: "Which law states that the current through a conductor is directly proportional to the voltage across it?",
    options: ["Newton's Law", "Ohm's Law", "Faraday's Law", "Coulomb's Law"],
    correctAnswer: 1,
    subject: "Physics",
    difficulty: "easy",
  },
  {
    id: 4,
    question: "What is the acceleration due to gravity on Earth?",
    options: ["8.9 m/s²", "9.8 m/s²", "10.8 m/s²", "11.8 m/s²"],
    correctAnswer: 1,
    subject: "Physics",
    difficulty: "easy",
  },
  {
    id: 5,
    question: "Which of the following is a vector quantity?",
    options: ["Mass", "Temperature", "Velocity", "Energy"],
    correctAnswer: 2,
    subject: "Physics",
    difficulty: "medium",
  },
  {
    id: 6,
    question: "The phenomenon of splitting of white light into its constituent colors is called:",
    options: ["Reflection", "Refraction", "Dispersion", "Diffraction"],
    correctAnswer: 2,
    subject: "Physics",
    difficulty: "medium",
  },
  {
    id: 7,
    question: "What is the unit of electrical resistance?",
    options: ["Volt", "Ampere", "Ohm", "Watt"],
    correctAnswer: 2,
    subject: "Physics",
    difficulty: "easy",
  },
  {
    id: 8,
    question: "In a parallel circuit, which quantity remains the same across all components?",
    options: ["Current", "Voltage", "Resistance", "Power"],
    correctAnswer: 1,
    subject: "Physics",
    difficulty: "medium",
  },
  {
    id: 9,
    question: "The energy possessed by a body due to its motion is called:",
    options: ["Potential Energy", "Kinetic Energy", "Thermal Energy", "Nuclear Energy"],
    correctAnswer: 1,
    subject: "Physics",
    difficulty: "easy",
  },
  {
    id: 10,
    question: "Which electromagnetic wave has the highest frequency?",
    options: ["Radio waves", "Microwaves", "X-rays", "Gamma rays"],
    correctAnswer: 3,
    subject: "Physics",
    difficulty: "medium",
  },
  {
    id: 11,
    question: "What is the formula for momentum?",
    options: ["p = mv", "p = ma", "p = m/v", "p = v/m"],
    correctAnswer: 0,
    subject: "Physics",
    difficulty: "easy",
  },
  {
    id: 12,
    question: "The unit of frequency is:",
    options: ["Second", "Meter", "Hertz", "Newton"],
    correctAnswer: 2,
    subject: "Physics",
    difficulty: "easy",
  },
  {
    id: 13,
    question: "What type of mirror is used in car headlights?",
    options: ["Plane mirror", "Convex mirror", "Concave mirror", "Cylindrical mirror"],
    correctAnswer: 2,
    subject: "Physics",
    difficulty: "medium",
  },
  {
    id: 14,
    question: "The principle of conservation of momentum is derived from:",
    options: ["Newton's First Law", "Newton's Second Law", "Newton's Third Law", "Law of Gravitation"],
    correctAnswer: 2,
    subject: "Physics",
    difficulty: "medium",
  },
  {
    id: 15,
    question: "What is the SI unit of electric current?",
    options: ["Volt", "Ohm", "Ampere", "Coulomb"],
    correctAnswer: 2,
    subject: "Physics",
    difficulty: "easy",
  },
  {
    id: 16,
    question: "The refractive index of air is approximately:",
    options: ["0", "1", "1.5", "2"],
    correctAnswer: 1,
    subject: "Physics",
    difficulty: "medium",
  },
  {
    id: 17,
    question: "Which particle has a positive charge?",
    options: ["Electron", "Proton", "Neutron", "Photon"],
    correctAnswer: 1,
    subject: "Physics",
    difficulty: "easy",
  },
  {
    id: 18,
    question: "The dimensional formula of work is:",
    options: ["[MLT⁻¹]", "[ML²T⁻²]", "[MLT⁻²]", "[ML²T⁻¹]"],
    correctAnswer: 1,
    subject: "Physics",
    difficulty: "hard",
  },
  {
    id: 19,
    question: "What is the escape velocity from Earth?",
    options: ["8 km/s", "11.2 km/s", "15 km/s", "20 km/s"],
    correctAnswer: 1,
    subject: "Physics",
    difficulty: "hard",
  },
  {
    id: 20,
    question: "In which medium does sound travel fastest?",
    options: ["Air", "Water", "Steel", "Vacuum"],
    correctAnswer: 2,
    subject: "Physics",
    difficulty: "medium",
  },
  {
    id: 21,
    question: "The angle of incidence equals the angle of reflection. This is the law of:",
    options: ["Refraction", "Reflection", "Diffraction", "Interference"],
    correctAnswer: 1,
    subject: "Physics",
    difficulty: "easy",
  },
  {
    id: 22,
    question: "What is the SI unit of power?",
    options: ["Joule", "Newton", "Watt", "Pascal"],
    correctAnswer: 2,
    subject: "Physics",
    difficulty: "easy",
  },
  {
    id: 23,
    question: "A transformer works on the principle of:",
    options: ["Self induction", "Mutual induction", "Electrolysis", "Photoelectric effect"],
    correctAnswer: 1,
    subject: "Physics",
    difficulty: "medium",
  },
  {
    id: 24,
    question: "The efficiency of a Carnot engine depends on:",
    options: ["Working substance", "Temperature of source and sink", "Size of engine", "Pressure of gas"],
    correctAnswer: 1,
    subject: "Physics",
    difficulty: "hard",
  },
  {
    id: 25,
    question: "What is the focal length of a plane mirror?",
    options: ["Zero", "Infinity", "One meter", "Variable"],
    correctAnswer: 1,
    subject: "Physics",
    difficulty: "medium",
  },
  {
    id: 26,
    question: "The unit of magnetic flux is:",
    options: ["Tesla", "Weber", "Gauss", "Ampere"],
    correctAnswer: 1,
    subject: "Physics",
    difficulty: "medium",
  },
  {
    id: 27,
    question: "Doppler effect is associated with:",
    options: ["Light only", "Sound only", "Both light and sound", "Neither"],
    correctAnswer: 2,
    subject: "Physics",
    difficulty: "medium",
  },
  {
    id: 28,
    question: "The time period of a simple pendulum depends on:",
    options: ["Mass of bob", "Length and g", "Amplitude", "Material of string"],
    correctAnswer: 1,
    subject: "Physics",
    difficulty: "medium",
  },
  {
    id: 29,
    question: "What is the value of Planck's constant?",
    options: ["6.63 × 10⁻³⁴ Js", "6.63 × 10⁻²⁴ Js", "6.63 × 10⁻¹⁴ Js", "6.63 × 10⁻⁴⁴ Js"],
    correctAnswer: 0,
    subject: "Physics",
    difficulty: "hard",
  },
  {
    id: 30,
    question: "Nuclear fusion requires:",
    options: ["Low temperature", "Very high temperature", "Normal temperature", "Low pressure"],
    correctAnswer: 1,
    subject: "Physics",
    difficulty: "medium",
  },

  // ========== CHEMISTRY (30 Questions) ==========
  {
    id: 31,
    question: "What is the atomic number of Carbon?",
    options: ["4", "6", "8", "12"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "easy",
  },
  {
    id: 32,
    question: "Which gas is most abundant in Earth's atmosphere?",
    options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"],
    correctAnswer: 2,
    subject: "Chemistry",
    difficulty: "easy",
  },
  {
    id: 33,
    question: "The pH value of a neutral solution is:",
    options: ["0", "7", "14", "1"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "easy",
  },
  {
    id: 34,
    question: "Which element is known as the 'King of Chemicals'?",
    options: ["Hydrochloric Acid", "Nitric Acid", "Sulphuric Acid", "Phosphoric Acid"],
    correctAnswer: 2,
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: 35,
    question: "What is the chemical formula of water?",
    options: ["HO", "H₂O", "H₂O₂", "HO₂"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "easy",
  },
  {
    id: 36,
    question: "Which type of bond is formed when electrons are shared between atoms?",
    options: ["Ionic bond", "Covalent bond", "Metallic bond", "Hydrogen bond"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: 37,
    question: "The process of conversion of solid directly to gas is called:",
    options: ["Evaporation", "Condensation", "Sublimation", "Deposition"],
    correctAnswer: 2,
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: 38,
    question: "Which element has the highest electronegativity?",
    options: ["Oxygen", "Chlorine", "Fluorine", "Nitrogen"],
    correctAnswer: 2,
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: 39,
    question: "What is the molar mass of NaCl?",
    options: ["40 g/mol", "58.5 g/mol", "74 g/mol", "98 g/mol"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: 40,
    question: "Which reaction releases energy?",
    options: ["Endothermic", "Exothermic", "Reversible", "Irreversible"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "easy",
  },
  {
    id: 41,
    question: "The number of electrons in the outermost shell of an element determines its:",
    options: ["Atomic mass", "Valency", "Atomic number", "Density"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: 42,
    question: "What is the chemical formula of sulfuric acid?",
    options: ["HCl", "HNO₃", "H₂SO₄", "H₃PO₄"],
    correctAnswer: 2,
    subject: "Chemistry",
    difficulty: "easy",
  },
  {
    id: 43,
    question: "Which gas is produced when zinc reacts with hydrochloric acid?",
    options: ["Oxygen", "Hydrogen", "Nitrogen", "Chlorine"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: 44,
    question: "The process of rusting involves:",
    options: ["Reduction", "Oxidation", "Neutralization", "Decomposition"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: 45,
    question: "Which element is liquid at room temperature?",
    options: ["Sodium", "Mercury", "Iron", "Copper"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "easy",
  },
  {
    id: 46,
    question: "Avogadro's number is approximately:",
    options: ["6.02 × 10²³", "6.02 × 10²⁴", "6.02 × 10²²", "6.02 × 10²⁰"],
    correctAnswer: 0,
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: 47,
    question: "Which of these is a noble gas?",
    options: ["Nitrogen", "Oxygen", "Helium", "Hydrogen"],
    correctAnswer: 2,
    subject: "Chemistry",
    difficulty: "easy",
  },
  {
    id: 48,
    question: "The process of obtaining pure copper from impure copper is called:",
    options: ["Distillation", "Electrolysis", "Filtration", "Crystallization"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: 49,
    question: "What is the hybridization of carbon in methane?",
    options: ["sp", "sp²", "sp³", "sp³d"],
    correctAnswer: 2,
    subject: "Chemistry",
    difficulty: "hard",
  },
  {
    id: 50,
    question: "Which acid is found in vinegar?",
    options: ["Citric acid", "Acetic acid", "Formic acid", "Lactic acid"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "easy",
  },
  {
    id: 51,
    question: "The molecular geometry of water is:",
    options: ["Linear", "Trigonal planar", "Bent", "Tetrahedral"],
    correctAnswer: 2,
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: 52,
    question: "Which catalyst is used in the Haber process?",
    options: ["Platinum", "Iron", "Nickel", "Copper"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "hard",
  },
  {
    id: 53,
    question: "The functional group -OH is characteristic of:",
    options: ["Aldehydes", "Ketones", "Alcohols", "Carboxylic acids"],
    correctAnswer: 2,
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: 54,
    question: "What is the oxidation state of oxygen in most compounds?",
    options: ["-1", "-2", "+2", "+1"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: 55,
    question: "Which law states that equal volumes of gases at same temperature and pressure contain equal number of molecules?",
    options: ["Boyle's Law", "Charles's Law", "Avogadro's Law", "Dalton's Law"],
    correctAnswer: 2,
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: 56,
    question: "The IUPAC name of CH₃CHO is:",
    options: ["Methanol", "Ethanal", "Propanol", "Butanal"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "hard",
  },
  {
    id: 57,
    question: "Which element has the electronic configuration 1s² 2s² 2p⁶ 3s¹?",
    options: ["Lithium", "Sodium", "Potassium", "Magnesium"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: 58,
    question: "Baking soda is chemically:",
    options: ["Sodium chloride", "Sodium carbonate", "Sodium bicarbonate", "Sodium hydroxide"],
    correctAnswer: 2,
    subject: "Chemistry",
    difficulty: "easy",
  },
  {
    id: 59,
    question: "The bond angle in ammonia is approximately:",
    options: ["90°", "107°", "109.5°", "120°"],
    correctAnswer: 1,
    subject: "Chemistry",
    difficulty: "hard",
  },
  {
    id: 60,
    question: "Which type of isomerism is shown by CH₃OCH₃ and C₂H₅OH?",
    options: ["Chain isomerism", "Position isomerism", "Functional isomerism", "Geometric isomerism"],
    correctAnswer: 2,
    subject: "Chemistry",
    difficulty: "hard",
  },

  // ========== MATHEMATICS (30 Questions) ==========
  {
    id: 61,
    question: "What is the value of π (pi) approximately?",
    options: ["2.14", "3.14", "4.14", "5.14"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "easy",
  },
  {
    id: 62,
    question: "What is the derivative of x²?",
    options: ["x", "2x", "x²", "2x²"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "medium",
  },
  {
    id: 63,
    question: "If sin θ = 1/2, what is θ?",
    options: ["30°", "45°", "60°", "90°"],
    correctAnswer: 0,
    subject: "Mathematics",
    difficulty: "medium",
  },
  {
    id: 64,
    question: "What is the sum of interior angles of a triangle?",
    options: ["90°", "180°", "270°", "360°"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "easy",
  },
  {
    id: 65,
    question: "What is the integral of 1/x?",
    options: ["x", "1/x²", "ln|x| + C", "e^x"],
    correctAnswer: 2,
    subject: "Mathematics",
    difficulty: "hard",
  },
  {
    id: 66,
    question: "What is the quadratic formula?",
    options: [
      "x = (-b ± √(b² - 4ac)) / 2a",
      "x = (-b ± √(b² + 4ac)) / 2a",
      "x = (b ± √(b² - 4ac)) / 2a",
      "x = (-b ± √(b² - 4ac)) / a",
    ],
    correctAnswer: 0,
    subject: "Mathematics",
    difficulty: "medium",
  },
  {
    id: 67,
    question: "What is log₁₀(100)?",
    options: ["1", "2", "10", "100"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "easy",
  },
  {
    id: 68,
    question: "What is the factorial of 5 (5!)?",
    options: ["25", "60", "120", "720"],
    correctAnswer: 2,
    subject: "Mathematics",
    difficulty: "easy",
  },
  {
    id: 69,
    question: "In a right triangle, what is the Pythagorean theorem?",
    options: ["a + b = c", "a² + b² = c²", "a × b = c", "a/b = c"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "easy",
  },
  {
    id: 70,
    question: "What is the limit of (1 + 1/n)^n as n approaches infinity?",
    options: ["1", "2", "e", "π"],
    correctAnswer: 2,
    subject: "Mathematics",
    difficulty: "hard",
  },
  {
    id: 71,
    question: "What is the derivative of sin(x)?",
    options: ["-sin(x)", "cos(x)", "-cos(x)", "tan(x)"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "medium",
  },
  {
    id: 72,
    question: "The value of cos(0°) is:",
    options: ["0", "1", "-1", "1/2"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "easy",
  },
  {
    id: 73,
    question: "What is the sum of first n natural numbers?",
    options: ["n(n-1)/2", "n(n+1)/2", "n²/2", "n(n+1)"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "medium",
  },
  {
    id: 74,
    question: "The inverse of matrix A exists if:",
    options: ["|A| = 0", "|A| ≠ 0", "|A| = 1", "|A| < 0"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "medium",
  },
  {
    id: 75,
    question: "What is the value of tan(45°)?",
    options: ["0", "1", "√3", "1/√3"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "easy",
  },
  {
    id: 76,
    question: "The equation of a circle with center (0,0) and radius r is:",
    options: ["x + y = r", "x² + y² = r²", "x² - y² = r²", "xy = r"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "medium",
  },
  {
    id: 77,
    question: "What is the integral of e^x?",
    options: ["e^x + C", "xe^x + C", "e^x/x + C", "ln(e^x) + C"],
    correctAnswer: 0,
    subject: "Mathematics",
    difficulty: "medium",
  },
  {
    id: 78,
    question: "The number of permutations of n objects taken r at a time is:",
    options: ["n!/r!", "n!/(n-r)!", "r!/(n-r)!", "n!/((n-r)!r!)"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "hard",
  },
  {
    id: 79,
    question: "What is the slope of a line parallel to x-axis?",
    options: ["0", "1", "Infinity", "Undefined"],
    correctAnswer: 0,
    subject: "Mathematics",
    difficulty: "easy",
  },
  {
    id: 80,
    question: "The sum of a geometric series a + ar + ar² + ... to infinity (|r| < 1) is:",
    options: ["a/(1-r)", "a/(1+r)", "ar/(1-r)", "a(1-r)"],
    correctAnswer: 0,
    subject: "Mathematics",
    difficulty: "hard",
  },
  {
    id: 81,
    question: "What is the second derivative of x³?",
    options: ["3x²", "6x", "3x", "6x²"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "medium",
  },
  {
    id: 82,
    question: "The dot product of perpendicular vectors is:",
    options: ["1", "-1", "0", "Infinity"],
    correctAnswer: 2,
    subject: "Mathematics",
    difficulty: "medium",
  },
  {
    id: 83,
    question: "sin²θ + cos²θ equals:",
    options: ["0", "1", "2", "sin2θ"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "easy",
  },
  {
    id: 84,
    question: "The area under the curve y = f(x) from x = a to x = b is:",
    options: ["∫f(x)dx from a to b", "f(b) - f(a)", "f'(x)", "dy/dx"],
    correctAnswer: 0,
    subject: "Mathematics",
    difficulty: "medium",
  },
  {
    id: 85,
    question: "What is the value of i² (where i = √-1)?",
    options: ["1", "-1", "i", "-i"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "medium",
  },
  {
    id: 86,
    question: "The binomial coefficient C(n,r) is equal to:",
    options: ["n!/(r!(n-r)!)", "n!/r!", "(n-r)!/r!", "n!/(n-r)!"],
    correctAnswer: 0,
    subject: "Mathematics",
    difficulty: "hard",
  },
  {
    id: 87,
    question: "What is the period of sin(x)?",
    options: ["π", "2π", "π/2", "4π"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "medium",
  },
  {
    id: 88,
    question: "The eccentricity of a circle is:",
    options: ["0", "1", "Greater than 1", "Less than 1"],
    correctAnswer: 0,
    subject: "Mathematics",
    difficulty: "hard",
  },
  {
    id: 89,
    question: "What is the cross product of parallel vectors?",
    options: ["Maximum", "Zero vector", "Unit vector", "Undefined"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "medium",
  },
  {
    id: 90,
    question: "L'Hôpital's rule is used for finding:",
    options: ["Derivatives", "Integrals", "Indeterminate limits", "Series convergence"],
    correctAnswer: 2,
    subject: "Mathematics",
    difficulty: "hard",
  },

  // ========== BIOLOGY (30 Questions) ==========
  {
    id: 91,
    question: "What is the powerhouse of the cell?",
    options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi apparatus"],
    correctAnswer: 2,
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: 92,
    question: "DNA stands for:",
    options: [
      "Deoxyribonucleic Acid",
      "Dinitrogen Acid",
      "Deoxyribose Nucleic Acid",
      "Double Nucleic Acid",
    ],
    correctAnswer: 0,
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: 93,
    question: "Which blood group is known as the universal donor?",
    options: ["A", "B", "AB", "O"],
    correctAnswer: 3,
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: 94,
    question: "The process by which plants make their own food is called:",
    options: ["Respiration", "Photosynthesis", "Transpiration", "Digestion"],
    correctAnswer: 1,
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: 95,
    question: "How many chromosomes are in a human cell?",
    options: ["23", "44", "46", "48"],
    correctAnswer: 2,
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: 96,
    question: "Which vitamin is produced when skin is exposed to sunlight?",
    options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"],
    correctAnswer: 3,
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: 97,
    question: "The largest organ in the human body is:",
    options: ["Heart", "Liver", "Skin", "Brain"],
    correctAnswer: 2,
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: 98,
    question: "Which enzyme breaks down starch?",
    options: ["Pepsin", "Lipase", "Amylase", "Trypsin"],
    correctAnswer: 2,
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: 99,
    question: "Red blood cells are produced in the:",
    options: ["Heart", "Liver", "Bone marrow", "Kidneys"],
    correctAnswer: 2,
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: 100,
    question: "The basic unit of life is:",
    options: ["Atom", "Molecule", "Cell", "Tissue"],
    correctAnswer: 2,
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: 101,
    question: "Which organelle is responsible for protein synthesis?",
    options: ["Mitochondria", "Ribosome", "Nucleus", "Lysosome"],
    correctAnswer: 1,
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: 102,
    question: "The exchange of gases in lungs takes place in:",
    options: ["Bronchi", "Trachea", "Alveoli", "Bronchioles"],
    correctAnswer: 2,
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: 103,
    question: "Which hormone regulates blood sugar level?",
    options: ["Thyroxine", "Insulin", "Adrenaline", "Estrogen"],
    correctAnswer: 1,
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: 104,
    question: "The study of heredity is called:",
    options: ["Ecology", "Genetics", "Anatomy", "Physiology"],
    correctAnswer: 1,
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: 105,
    question: "Which type of muscle is found in the heart?",
    options: ["Smooth muscle", "Skeletal muscle", "Cardiac muscle", "Voluntary muscle"],
    correctAnswer: 2,
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: 106,
    question: "The pH of human blood is approximately:",
    options: ["6.4", "7.0", "7.4", "8.0"],
    correctAnswer: 2,
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: 107,
    question: "Which part of the brain controls balance?",
    options: ["Cerebrum", "Cerebellum", "Medulla", "Thalamus"],
    correctAnswer: 1,
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: 108,
    question: "Chlorophyll is found in:",
    options: ["Mitochondria", "Chloroplast", "Nucleus", "Ribosome"],
    correctAnswer: 1,
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: 109,
    question: "The process of cell division in somatic cells is called:",
    options: ["Meiosis", "Mitosis", "Binary fission", "Budding"],
    correctAnswer: 1,
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: 110,
    question: "Which blood cells help in clotting?",
    options: ["RBC", "WBC", "Platelets", "Plasma"],
    correctAnswer: 2,
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: 111,
    question: "The universal blood recipient is:",
    options: ["A", "B", "AB", "O"],
    correctAnswer: 2,
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: 112,
    question: "ATP stands for:",
    options: [
      "Adenosine Triphosphate",
      "Adenosine Diphosphate",
      "Amino Triphosphate",
      "Adenine Triphosphate",
    ],
    correctAnswer: 0,
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: 113,
    question: "The longest bone in the human body is:",
    options: ["Humerus", "Tibia", "Femur", "Radius"],
    correctAnswer: 2,
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: 114,
    question: "Which gland is known as the master gland?",
    options: ["Thyroid", "Pituitary", "Adrenal", "Pancreas"],
    correctAnswer: 1,
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: 115,
    question: "The theory of evolution was proposed by:",
    options: ["Gregor Mendel", "Louis Pasteur", "Charles Darwin", "Robert Hooke"],
    correctAnswer: 2,
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: 116,
    question: "Which nucleotide base is not found in RNA?",
    options: ["Adenine", "Guanine", "Thymine", "Uracil"],
    correctAnswer: 2,
    subject: "Biology",
    difficulty: "hard",
  },
  {
    id: 117,
    question: "The process of breaking down glucose to release energy is called:",
    options: ["Photosynthesis", "Respiration", "Fermentation", "Digestion"],
    correctAnswer: 1,
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: 118,
    question: "Vaccination provides which type of immunity?",
    options: ["Natural active", "Natural passive", "Artificial active", "Artificial passive"],
    correctAnswer: 2,
    subject: "Biology",
    difficulty: "hard",
  },
  {
    id: 119,
    question: "The functional unit of kidney is:",
    options: ["Neuron", "Nephron", "Alveolus", "Glomerulus"],
    correctAnswer: 1,
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: 120,
    question: "Which vitamin deficiency causes night blindness?",
    options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"],
    correctAnswer: 0,
    subject: "Biology",
    difficulty: "medium",
  },

  // ========== ENGLISH (20 Questions) ==========
  {
    id: 121,
    question: "Which of the following is a synonym of 'Abundant'?",
    options: ["Scarce", "Plentiful", "Limited", "Rare"],
    correctAnswer: 1,
    subject: "English",
    difficulty: "easy",
  },
  {
    id: 122,
    question: "What is the antonym of 'Benevolent'?",
    options: ["Kind", "Generous", "Malevolent", "Charitable"],
    correctAnswer: 2,
    subject: "English",
    difficulty: "medium",
  },
  {
    id: 123,
    question: "Choose the correctly spelled word:",
    options: ["Accomodate", "Accommodate", "Acommodate", "Acomodate"],
    correctAnswer: 1,
    subject: "English",
    difficulty: "medium",
  },
  {
    id: 124,
    question: "What type of noun is 'happiness'?",
    options: ["Common noun", "Proper noun", "Abstract noun", "Collective noun"],
    correctAnswer: 2,
    subject: "English",
    difficulty: "easy",
  },
  {
    id: 125,
    question: "The word 'quickly' is what part of speech?",
    options: ["Adjective", "Adverb", "Verb", "Noun"],
    correctAnswer: 1,
    subject: "English",
    difficulty: "easy",
  },
  {
    id: 126,
    question: "Which sentence is grammatically correct?",
    options: [
      "He don't know the answer",
      "He doesn't knows the answer",
      "He doesn't know the answer",
      "He not know the answer",
    ],
    correctAnswer: 2,
    subject: "English",
    difficulty: "easy",
  },
  {
    id: 127,
    question: "What is the plural of 'phenomenon'?",
    options: ["Phenomenons", "Phenomena", "Phenomenas", "Phenomenen"],
    correctAnswer: 1,
    subject: "English",
    difficulty: "medium",
  },
  {
    id: 128,
    question: "'To let the cat out of the bag' means:",
    options: [
      "To release a cat",
      "To reveal a secret",
      "To lose something",
      "To buy a pet",
    ],
    correctAnswer: 1,
    subject: "English",
    difficulty: "medium",
  },
  {
    id: 129,
    question: "What is the past tense of 'begin'?",
    options: ["Beginned", "Began", "Begun", "Beginning"],
    correctAnswer: 1,
    subject: "English",
    difficulty: "easy",
  },
  {
    id: 130,
    question: "A person who studies languages is called a:",
    options: ["Linguist", "Physicist", "Biologist", "Chemist"],
    correctAnswer: 0,
    subject: "English",
    difficulty: "easy",
  },
  {
    id: 131,
    question: "The synonym of 'Ephemeral' is:",
    options: ["Permanent", "Transient", "Eternal", "Lasting"],
    correctAnswer: 1,
    subject: "English",
    difficulty: "hard",
  },
  {
    id: 132,
    question: "Which sentence uses the correct form of 'their/there/they're'?",
    options: [
      "Their going to the park",
      "They're books are on the table",
      "There going to be late",
      "They're planning to visit tomorrow",
    ],
    correctAnswer: 3,
    subject: "English",
    difficulty: "medium",
  },
  {
    id: 133,
    question: "'A stitch in time saves nine' is an example of:",
    options: ["Simile", "Metaphor", "Proverb", "Hyperbole"],
    correctAnswer: 2,
    subject: "English",
    difficulty: "easy",
  },
  {
    id: 134,
    question: "The antonym of 'Verbose' is:",
    options: ["Wordy", "Lengthy", "Concise", "Elaborate"],
    correctAnswer: 2,
    subject: "English",
    difficulty: "hard",
  },
  {
    id: 135,
    question: "Which word is a conjunction?",
    options: ["Quickly", "Although", "Beautiful", "Running"],
    correctAnswer: 1,
    subject: "English",
    difficulty: "medium",
  },
  {
    id: 136,
    question: "The collective noun for a group of fish is:",
    options: ["Herd", "Flock", "School", "Pack"],
    correctAnswer: 2,
    subject: "English",
    difficulty: "easy",
  },
  {
    id: 137,
    question: "'He is as brave as a lion' is an example of:",
    options: ["Metaphor", "Simile", "Personification", "Alliteration"],
    correctAnswer: 1,
    subject: "English",
    difficulty: "easy",
  },
  {
    id: 138,
    question: "What is the superlative form of 'good'?",
    options: ["Gooder", "Better", "Best", "Most good"],
    correctAnswer: 2,
    subject: "English",
    difficulty: "easy",
  },
  {
    id: 139,
    question: "The passive voice of 'She writes a letter' is:",
    options: [
      "A letter is written by her",
      "A letter was written by her",
      "A letter has been written by her",
      "A letter will be written by her",
    ],
    correctAnswer: 0,
    subject: "English",
    difficulty: "medium",
  },
  {
    id: 140,
    question: "Which sentence contains a gerund?",
    options: [
      "She is running fast",
      "Running is good exercise",
      "She runs every day",
      "She will run tomorrow",
    ],
    correctAnswer: 1,
    subject: "English",
    difficulty: "hard",
  },

  // ========== BASIC MATHS (20 Questions) ==========
  {
    id: 141,
    question: "What is 15% of 200?",
    options: ["25", "30", "35", "40"],
    correctAnswer: 1,
    subject: "Basic Maths",
    difficulty: "easy",
  },
  {
    id: 142,
    question: "If a = 3 and b = 4, what is a² + b²?",
    options: ["7", "12", "25", "49"],
    correctAnswer: 2,
    subject: "Basic Maths",
    difficulty: "easy",
  },
  {
    id: 143,
    question: "What is the LCM of 12 and 18?",
    options: ["6", "36", "72", "216"],
    correctAnswer: 1,
    subject: "Basic Maths",
    difficulty: "medium",
  },
  {
    id: 144,
    question: "Simplify: 3/4 + 1/2",
    options: ["1", "5/4", "4/6", "1/4"],
    correctAnswer: 1,
    subject: "Basic Maths",
    difficulty: "easy",
  },
  {
    id: 145,
    question: "What is the square root of 144?",
    options: ["10", "11", "12", "13"],
    correctAnswer: 2,
    subject: "Basic Maths",
    difficulty: "easy",
  },
  {
    id: 146,
    question: "If 2x + 5 = 15, what is x?",
    options: ["5", "10", "7.5", "2.5"],
    correctAnswer: 0,
    subject: "Basic Maths",
    difficulty: "easy",
  },
  {
    id: 147,
    question: "What is the area of a rectangle with length 8 and width 5?",
    options: ["13", "26", "40", "80"],
    correctAnswer: 2,
    subject: "Basic Maths",
    difficulty: "easy",
  },
  {
    id: 148,
    question: "What is 2³ × 3²?",
    options: ["36", "48", "72", "108"],
    correctAnswer: 2,
    subject: "Basic Maths",
    difficulty: "medium",
  },
  {
    id: 149,
    question: "A train travels 120 km in 2 hours. What is its speed?",
    options: ["40 km/h", "50 km/h", "60 km/h", "70 km/h"],
    correctAnswer: 2,
    subject: "Basic Maths",
    difficulty: "easy",
  },
  {
    id: 150,
    question: "If the ratio of boys to girls is 3:2 and there are 30 boys, how many girls are there?",
    options: ["15", "20", "25", "45"],
    correctAnswer: 1,
    subject: "Basic Maths",
    difficulty: "medium",
  },
  {
    id: 151,
    question: "What is the GCD of 24 and 36?",
    options: ["6", "8", "12", "18"],
    correctAnswer: 2,
    subject: "Basic Maths",
    difficulty: "medium",
  },
  {
    id: 152,
    question: "What is 25% of 80?",
    options: ["15", "20", "25", "30"],
    correctAnswer: 1,
    subject: "Basic Maths",
    difficulty: "easy",
  },
  {
    id: 153,
    question: "If a book costs $40 with a 20% discount, what is the sale price?",
    options: ["$28", "$30", "$32", "$36"],
    correctAnswer: 2,
    subject: "Basic Maths",
    difficulty: "medium",
  },
  {
    id: 154,
    question: "What is the perimeter of a square with side 7 cm?",
    options: ["14 cm", "21 cm", "28 cm", "49 cm"],
    correctAnswer: 2,
    subject: "Basic Maths",
    difficulty: "easy",
  },
  {
    id: 155,
    question: "Simplify: (8 + 4) × 2 - 6",
    options: ["14", "18", "20", "24"],
    correctAnswer: 1,
    subject: "Basic Maths",
    difficulty: "easy",
  },
  {
    id: 156,
    question: "What is the average of 10, 15, 20, 25, and 30?",
    options: ["18", "20", "22", "25"],
    correctAnswer: 1,
    subject: "Basic Maths",
    difficulty: "easy",
  },
  {
    id: 157,
    question: "If 3x - 7 = 14, what is x?",
    options: ["5", "7", "9", "11"],
    correctAnswer: 1,
    subject: "Basic Maths",
    difficulty: "medium",
  },
  {
    id: 158,
    question: "What is the volume of a cube with side 3 cm?",
    options: ["9 cm³", "18 cm³", "27 cm³", "36 cm³"],
    correctAnswer: 2,
    subject: "Basic Maths",
    difficulty: "medium",
  },
  {
    id: 159,
    question: "Express 0.75 as a fraction:",
    options: ["1/2", "2/3", "3/4", "4/5"],
    correctAnswer: 2,
    subject: "Basic Maths",
    difficulty: "easy",
  },
  {
    id: 160,
    question: "A car travels 150 km using 10 liters of fuel. What is its mileage?",
    options: ["10 km/l", "12 km/l", "15 km/l", "20 km/l"],
    correctAnswer: 2,
    subject: "Basic Maths",
    difficulty: "medium",
  },

  // ========== ADVANCED MATHS (10 Questions) ==========
  {
    id: 161,
    question: "What is the general solution of d²y/dx² + y = 0?",
    options: [
      "y = Ae^x + Be^(-x)",
      "y = A cos x + B sin x",
      "y = Ax + B",
      "y = A sin x",
    ],
    correctAnswer: 1,
    subject: "Advanced Maths",
    difficulty: "hard",
  },
  {
    id: 162,
    question: "The determinant of a 2×2 matrix [[a,b],[c,d]] is:",
    options: ["ac - bd", "ad - bc", "ab - cd", "ad + bc"],
    correctAnswer: 1,
    subject: "Advanced Maths",
    difficulty: "medium",
  },
  {
    id: 163,
    question: "What is the dot product of vectors (1,2,3) and (4,5,6)?",
    options: ["12", "24", "32", "48"],
    correctAnswer: 2,
    subject: "Advanced Maths",
    difficulty: "medium",
  },
  {
    id: 164,
    question: "The Laplace transform of e^(at) is:",
    options: ["1/(s-a)", "1/(s+a)", "s/(s-a)", "a/(s-a)"],
    correctAnswer: 0,
    subject: "Advanced Maths",
    difficulty: "hard",
  },
  {
    id: 165,
    question: "What is the eigenvalue equation for a matrix A?",
    options: ["Av = λv", "A + v = λ", "Av = v/λ", "A = λv"],
    correctAnswer: 0,
    subject: "Advanced Maths",
    difficulty: "hard",
  },
  {
    id: 166,
    question: "The rank of an identity matrix of order n is:",
    options: ["0", "1", "n", "n²"],
    correctAnswer: 2,
    subject: "Advanced Maths",
    difficulty: "medium",
  },
  {
    id: 167,
    question: "The gradient of a scalar function φ gives:",
    options: ["A scalar", "A vector", "A matrix", "Zero"],
    correctAnswer: 1,
    subject: "Advanced Maths",
    difficulty: "hard",
  },
  {
    id: 168,
    question: "The Fourier series represents a function as:",
    options: [
      "Sum of polynomials",
      "Sum of exponentials",
      "Sum of sines and cosines",
      "Sum of logarithms",
    ],
    correctAnswer: 2,
    subject: "Advanced Maths",
    difficulty: "hard",
  },
  {
    id: 169,
    question: "If f(x) = x³ - 3x + 2, the critical points are at:",
    options: ["x = 0, 3", "x = ±1", "x = ±2", "x = 1, 2"],
    correctAnswer: 1,
    subject: "Advanced Maths",
    difficulty: "hard",
  },
  {
    id: 170,
    question: "The divergence of a vector field F = (x², y², z²) at point (1,1,1) is:",
    options: ["3", "6", "9", "12"],
    correctAnswer: 1,
    subject: "Advanced Maths",
    difficulty: "hard",
  },

  // ========== DESIGN APTITUDE (10 Questions) ==========
  {
    id: 171,
    question: "The three primary colors in the RGB color model are:",
    options: [
      "Red, Yellow, Blue",
      "Red, Green, Blue",
      "Cyan, Magenta, Yellow",
      "Red, Orange, Yellow",
    ],
    correctAnswer: 1,
    subject: "Design Aptitude",
    difficulty: "easy",
  },
  {
    id: 172,
    question: "The Golden Ratio is approximately:",
    options: ["1.414", "1.618", "2.718", "3.142"],
    correctAnswer: 1,
    subject: "Design Aptitude",
    difficulty: "medium",
  },
  {
    id: 173,
    question: "Which principle of design refers to the distribution of visual weight?",
    options: ["Rhythm", "Balance", "Emphasis", "Unity"],
    correctAnswer: 1,
    subject: "Design Aptitude",
    difficulty: "medium",
  },
  {
    id: 174,
    question: "Complementary colors are located:",
    options: [
      "Next to each other on the color wheel",
      "Opposite each other on the color wheel",
      "At 90 degrees on the color wheel",
      "At 120 degrees on the color wheel",
    ],
    correctAnswer: 1,
    subject: "Design Aptitude",
    difficulty: "medium",
  },
  {
    id: 175,
    question: "An isometric view shows an object at what angle?",
    options: ["30°", "45°", "60°", "90°"],
    correctAnswer: 0,
    subject: "Design Aptitude",
    difficulty: "hard",
  },
  {
    id: 176,
    question: "Which color model is used for print media?",
    options: ["RGB", "CMYK", "HSL", "HSV"],
    correctAnswer: 1,
    subject: "Design Aptitude",
    difficulty: "easy",
  },
  {
    id: 177,
    question: "The technique of creating depth using overlapping objects is called:",
    options: ["Perspective", "Shading", "Foreshortening", "Occlusion"],
    correctAnswer: 3,
    subject: "Design Aptitude",
    difficulty: "medium",
  },
  {
    id: 178,
    question: "White space in design is also known as:",
    options: ["Dead space", "Negative space", "Empty space", "Void space"],
    correctAnswer: 1,
    subject: "Design Aptitude",
    difficulty: "easy",
  },
  {
    id: 179,
    question: "The rule of thirds divides an image into:",
    options: ["6 equal parts", "9 equal parts", "12 equal parts", "4 equal parts"],
    correctAnswer: 1,
    subject: "Design Aptitude",
    difficulty: "medium",
  },
  {
    id: 180,
    question: "In perspective drawing, parallel lines appear to converge at:",
    options: ["Horizon line", "Vanishing point", "Ground plane", "Eye level"],
    correctAnswer: 1,
    subject: "Design Aptitude",
    difficulty: "medium",
  },
];

export function getQuestionsForCategory(categoryId: string): Question[] {
  const category = testCategories.find((c) => c.id === categoryId);
  if (!category) return [];

  const subjectQuestions = allQuestions.filter((q) =>
    category.subjects.includes(q.subject)
  );

  return shuffleArray(subjectQuestions);
}

export function getCustomQuestions(
  subjects: string[],
  count: number,
  difficulty?: string
): Question[] {
  let filtered = allQuestions.filter((q) => subjects.includes(q.subject));

  if (difficulty && difficulty !== "mixed") {
    filtered = filtered.filter((q) => q.difficulty === difficulty);
  }

  return shuffleArray(filtered).slice(0, count);
}

function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

export const availableSubjects = [
  "Physics",
  "Chemistry",
  "Mathematics",
  "Biology",
  "English",
  "Basic Maths",
  "Advanced Maths",
  "Design Aptitude",
];

export function getSubjectCounts(): Record<string, { total: number; easy: number; medium: number; hard: number }> {
  const counts: Record<string, { total: number; easy: number; medium: number; hard: number }> = {};
  
  availableSubjects.forEach(subject => {
    const subjectQuestions = allQuestions.filter(q => q.subject === subject);
    counts[subject] = {
      total: subjectQuestions.length,
      easy: subjectQuestions.filter(q => q.difficulty === "easy").length,
      medium: subjectQuestions.filter(q => q.difficulty === "medium").length,
      hard: subjectQuestions.filter(q => q.difficulty === "hard").length,
    };
  });
  
  return counts;
}
